WebApplication/WebApplication/Controllers/DanhSachSanPhamController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Transactions;
using WebApplication.Models;
using System.IO;

namespace WebApplication.Controllers
{
    public class DanhSachSanPhamController : Controller
    {
        private CS4PEntities db = new CS4PEntities();

        // GET: /DanhSachSanPham/
        public ActionResult Index()
        {
            var bangsanphams = db.BangSanPhams.Include(b => b.LoaiSanPham);
            return View(bangsanphams.ToList());
        }

        // GET: /DanhSachSanPham/Details/5
        public FileResult Details(string id)
        {
            var path = Server.MapPath("~/App_Data");
            path = Path.Combine(path, id);
            return File(path, "images");
        }

        // GET: /DanhSachSanPham/Create
        public ActionResult Create()
        {
            ViewBag.Loai_id = new SelectList(db.LoaiSanPhams, "id", "TenLoai");
            return View();
        }

        // POST: /DanhSachSanPham/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BangSanPham model)
        {
            CheckBangSanPham(model);
            if (ModelState.IsValid)
            {
                using (var scope = new TransactionScope())
                {
                    db.BangSanPhams.Add(model);
                    db.SaveChanges();

                    if (Request.Files["HinhAnh"] != null &&
                        Request.Files["HinhAnh"].ContentLength > 0)
                    {
                        var path = Server.MapPath("~/App_Data");
                        path = System.IO.Path.Combine(path, model.id.ToString());
                        Request.Files["HinhAnh"].SaveAs(path);

                        scope.Complete();
                        return RedirectToAction("Index");
                    }
                    else
                        ModelState.AddModelError("HinhAnh", "Chua chon hinh anh cho san pham");
                }
            }

            ViewBag.Loai_id = new SelectList(db.LoaiSanPhams, "id", "TenLoai", model.Loai_id);
            return View(model);
        }

        private void CheckBangSanPham(BangSanPham model)
        {
            if (model.GiaGoc < 0)
                ModelState.AddModelError("GiaGoc", "Gia goc phai lon hon 0");
            if (model.GiaGoc > model.GiaBan)
                ModelState.AddModelError("GiaBan", "Gia ban phai lon hon gia goc");
            if (model.GiaGoc > model.GiaGop)
                ModelState.AddModelError("GiaGop", "Gia gop phai lon hon gia goc");
            if (model.SoLuongTon < 0)
                ModelState.AddModelError("SoLuongTon", "So luong ton phai lon hon 0");
        }

        // GET: /DanhSachSanPham/Edit/5
        public ActionResult Edit(int id)
        {
            BangSanPham model = db.BangSanPhams.Find(id);
            if (model == null)
            {
                return HttpNotFound();
            }
            ViewBag.Loai_id = new SelectList(db.LoaiSanPhams, "id", "TenLoai", model.Loai_id);
            return View(model);
        }

        // POST: /DanhSachSanPham/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(BangSanPham model)
        {
            CheckBangSanPham(model);
            if (ModelState.IsValid)
            {
                using (var scope = new TransactionScope())
                {
                    db.Entry(model).State = EntityState.Modified;
                    db.SaveChanges();

                    var path = Server.MapPath("~/App_Data");
                    path = path + "/" + model.id;
                    if (Request.Files["HinhAnh"] != null &&
                        Request.Files["HinhAnh"].ContentLength > 0)
                    {
                        Request.Files["HinhAnh"].SaveAs(path);
                    }

                    scope.Complete(); // approve for transaction
                    return RedirectToAction("Index");
                }
            }
            ViewBag.Loai_id = new SelectList(db.LoaiSanPhams, "id", "TenLoai", model.Loai_id);
            return View(model);
        }

        // GET: /DanhSachSanPham/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BangSanPham bangsanpham = db.BangSanPhams.Find(id);
            if (bangsanpham == null)
            {
                return HttpNotFound();
            }
            return View(bangsanpham);
        }

        // POST: /DanhSachSanPham/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BangSanPham bangsanpham = db.BangSanPhams.Find(id);
            db.BangSanPhams.Remove(bangsanpham);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication/WebApplication/Views/DanhSachSanPham/Create.cshtml
@model WebApplication.Models.BangSanPham

@{
    ViewBag.Title = "Create";
}

<h2>THÊM SẢN PHẨM</h2>


@using (Html.BeginForm("Create", "DanhSachSanPham", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.MaSP, "Mã SP", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.MaSP, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaSP)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenSP, "Tên sản phẩm", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.TenSP, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TenSP)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Loai_id, "Loại SP", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Loai_id, (IEnumerable<SelectListItem>)ViewData["Loai_id"], new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Loai_id)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaBan, "Giá bán", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.GiaBan, new { type = "number", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GiaBan)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaGoc, "Giá gốc", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.GiaGoc, new { type = "number", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GiaGoc)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaGop, "Giá góp", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.GiaGop, new { type = "number", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GiaGop)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoLuongTon, "Tồn kho", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.SoLuongTon, new { type = "number", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SoLuongTon)
            </div>
        </div>

        <div class="form-group">
            @Html.Label("HinhAnh", "Hình SP", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("HinhAnh", null, new { type = "file", accept = "image/gif, image/jpeg, image/png", onchange = "readURL(this);", @class = "form-control" })
                @Html.ValidationMessage("HinhAnh")
                <img id="HinhSP" src="" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
@Scripts.Render("~/bundles/jqueryval")
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
<script>
    $(document).ready(function () {
        $('#Loai_id').select2();
    });
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $('#HinhSP')
                    .attr('src', e.target.result);
                    //.width(150)
                    //.height(200);
            };
            reader.readAsDataURL(input.files[0]);
        }
    }
</script>
}

WebApplication/WebApplication/Views/DanhSachSanPham/Delete.cshtml
@model WebApplication.Models.BangSanPham

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BangSanPham</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MaSP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaSP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenSP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenSP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GiaBan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GiaBan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GiaGoc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GiaGoc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GiaGop)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GiaGop)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoLuongTon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLuongTon)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LoaiSanPham.TenLoai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiSanPham.TenLoai)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebApplication/WebApplication/Views/DanhSachSanPham/Details.cshtml
@model WebApplication.Models.BangSanPham

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>BangSanPham</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MaSP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaSP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenSP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenSP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GiaBan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GiaBan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GiaGoc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GiaGoc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GiaGop)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GiaGop)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoLuongTon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLuongTon)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LoaiSanPham.TenLoai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiSanPham.TenLoai)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebApplication/WebApplication/Views/DanhSachSanPham/Edit.cshtml
@model WebApplication.Models.BangSanPham

@{
    ViewBag.Title = "Edit";
}

<h2>CẬP NHẬT SP</h2>


@using (Html.BeginForm("Edit", "DanhSachSanPham", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.MaSP, "Mã SP", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.MaSP, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaSP)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenSP, "Tên sản phẩm", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.TenSP, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TenSP)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Loai_id, "Loại SP", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Loai_id, (IEnumerable<SelectListItem>)ViewData["Loai_id"], new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Loai_id)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaBan, "Giá bán", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.GiaBan, new { type = "number", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GiaBan)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaGoc, "Giá gốc", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.GiaGoc, new { type = "number", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GiaGoc)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaGop, "Giá góp", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.GiaGop, new { type = "number", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GiaGop)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoLuongTon, "Tồn kho", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.SoLuongTon, new { type = "number", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SoLuongTon)
            </div>
        </div>

        <div class="form-group">
            @Html.Label("HinhAnh", "Hình SP", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("HinhAnh", null, new { type = "file", onchange = "readURL(this);", @class = "form-control" })
                @Html.ValidationMessage("HinhAnh")
                <img id="HinhSP" src="@Url.Action("Details", new { id = Model.id })" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
@Scripts.Render("~/bundles/jqueryval")
<script>
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $('#HinhSP')
                    .attr('src', e.target.result);
                //.width(150)
                //.height(200);
            };
            reader.readAsDataURL(input.files[0]);
        }
    }
</script>
}

WebApplication/WebApplication/Views/DanhSachSanPham/Index.cshtml
@model IEnumerable<WebApplication.Models.BangSanPham>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table id="DanhSachSanPham" class="table">
    <thead>
        <tr>
            <th>Mã SP</th>
            <th>Tên SP</th>
            <th>Loại</th>
            <th>Giá bán</th>
            <th>Giá gốc</th>
            <th>Giá góp</th>
            <th>Tồn</th>
            <th>Hình ảnh</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.MaSP</td>
                <td>@item.TenSP</td>
                <td>@item.LoaiSanPham.TenLoai</td>
                <td>@item.GiaBan.ToString("N0")</td>
                <td>@item.GiaGoc.ToString("N0")</td>
                <td>@item.GiaGop.ToString("N0")</td>
                <td>@item.SoLuongTon.ToString("N0")</td>
                <td>
                    <img src="@Url.Action("Details", new  { id = item.id })" width="70" height="50" />
                </td>
                <td>
                    <a href="@Url.Action("Edit", new { id = item.id })">
                        <span class="glyphicon glyphicon-pencil"></span>
                    </a>
                    <a href="@Url.Action("Details", new{id = item.id})">
                        <span class="glyphicon glyphicon-search"></span>
                    </a>
                    <a href="@Url.Action("Delete", new { id = item.id })">
                        <span class="glyphicon glyphicon-trash"></span>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

@section scripts {
<link href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet" />
<script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script>
    $(document).ready(function () {
        $('#DanhSachSanPham').DataTable();
    });
</script>
}