WebApplication/WebApplication/Models/BangSanPham.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangSanPham
    {
        public BangSanPham()
        {
            this.ChiTietHDs = new HashSet<ChiTietHD>();
        }
    
        public int id { get; set; }
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public int Loai_id { get; set; }
        public int GiaBan { get; set; }
        public int GiaGoc { get; set; }
        public int GiaGop { get; set; }
        public int SoLuongTon { get; set; }
    
        public virtual LoaiSanPham LoaiSanPham { get; set; }
        public virtual ICollection<ChiTietHD> ChiTietHDs { get; set; }
    }
}

WebApplication/WebApplication/Controllers/BangSanPhamController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication.Models;
using System.Transactions;
namespace WebApplication.Controllers
{
    [Authorize]
    public class BangSanPhamController : Controller
    {
        private CS4PEntities db = new CS4PEntities();
        // GET: /BangSanPham/
        public ActionResult Index()
        {
            var bangsanphams = db.BangSanPhams.Include(b => b.LoaiSanPham);
            return View(bangsanphams.ToList());
        }

        // GET: /BangSanPham/Details/5
        public FileResult Details(string id)
        {
            var path = Server.MapPath("~/App_Data/" + id);
            return File(path, "images");
        }

        // GET: /Bangsanpham/Details/5
        public ActionResult Details1(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BangSanPham bangsanpham = db.BangSanPhams.Find(id);
            if (bangsanpham == null)
            {
                return HttpNotFound();
            }
            return View("Details", bangsanpham);
        }

        // GET: /BangSanPham/Create
        public ActionResult Create()
        {
            ViewBag.Loai_id = new SelectList(db.LoaiSanPhams, "id", "TenLoai");
            return View();
        }


        // POST: /BangSanPham/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BangSanPham model)
        {
            CheckBangSanPham(model);
            if (ModelState.IsValid)
            {
                using (var scope = new TransactionScope())
                {
                    db.BangSanPhams.Add(model);
                    db.SaveChanges();

                    var path = Server.MapPath("~/App_Data");
                    path = path + "/" + model.id;
                    if (Request.Files["HinhAnh"] != null &&
                        Request.Files["HinhAnh"].ContentLength > 0)
                    {
                        Request.Files["HinhAnh"].SaveAs(path);

                        scope.Complete(); // approve for transaction
                        return RedirectToAction("Index");
                    }
                    else
                        ModelState.AddModelError("HinhAnh", "Chưa có hình sản phẩm!");
                }
            }

            ViewBag.Loai_id = new SelectList(db.LoaiSanPhams, "id", "TenLoai", model.Loai_id);
            return View(model);
        }

        private void CheckBangSanPham(BangSanPham model)
        {
            if (model.GiaGoc < 0)
                ModelState.AddModelError("GiaGoc", "Giá gốc phải lớn hơn 0!");
            if (model.GiaBan < model.GiaGoc)
                ModelState.AddModelError("GiaBan", "Giá bán phải lớn hơn giá gốc!");
            if (model.GiaGop < model.GiaGoc)
                ModelState.AddModelError("GiaGop", "Giá góp phải lớn hơn giá gốc!");
        }

        // GET: /BangSanPham/Edit/5
        public ActionResult Edit(int id)
        {
            BangSanPham model = db.BangSanPhams.Find(id);
            if (model == null)
            {
                return HttpNotFound();
            }
            ViewBag.Loai_id = new SelectList(db.LoaiSanPhams, "id", "TenLoai", model.Loai_id);
            return View(model);
        }

        // POST: /BangSanPham/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(BangSanPham model)
        {
            CheckBangSanPham(model);
            if (ModelState.IsValid)
            {
                using (var scope = new TransactionScope())
                {
                    db.Entry(model).State = EntityState.Modified;
                    db.SaveChanges();

                    var path = Server.MapPath("~/App_Data");
                    path = path + "/" + model.id;
                    if (Request.Files["HinhAnh"] != null &&
                        Request.Files["HinhAnh"].ContentLength > 0)
                    {
                        Request.Files["HinhAnh"].SaveAs(path);
                    }

                    scope.Complete(); // approve for transaction
                    return RedirectToAction("Index");
                }
            }
            ViewBag.Loai_id = new SelectList(db.LoaiSanPhams, "id", "TenLoai", model.Loai_id);
            return View(model);
        }

        // GET: /BangSanPham/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BangSanPham bangsanpham = db.BangSanPhams.Find(id);
            if (bangsanpham == null)
            {
                return HttpNotFound();
            }
            return View(bangsanpham);
        }

        // POST: /BangSanPham/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BangSanPham bangsanpham = db.BangSanPhams.Find(id);
            db.BangSanPhams.Remove(bangsanpham);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication/WebApplication/Views/BangSanPham/Create.cshtml
@model WebApplication.Models.BangSanPham

@{
    ViewBag.Title = "Create";
}

<h2>Thêm sản phẩm mới</h2>


@using (Html.BeginForm("Create", "BangSanPham", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.MaSP, "Mã SP", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.MaSP, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaSP)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenSP, "Tên sản phẩm", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.TenSP, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TenSP)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Loai_id, "Loại", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Loai_id", (IEnumerable<SelectListItem>)ViewData["Loai_id"], new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Loai_id)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaGoc, "Giá gốc", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.GiaGoc, new { type = "number", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GiaGoc)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaBan, "Giá bán", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.GiaBan, new { type = "number", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GiaBan)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaGop, "Giá góp", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.GiaGop, new { type = "number", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GiaGop)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoLuongTon, "Số lượng", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.SoLuongTon, new { type = "number", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SoLuongTon)
            </div>
        </div>

        <div class="form-group">
            @Html.Label("HinhAnh", "Hình sản phẩm", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("HinhAnh", null, new { type = "file", onchange = "readURL(this)", @class = "form-control" })
                @Html.ValidationMessage("HinhAnh")
                <img id="HinhSP" src="" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay Lại", "Index")
</div>

@section Scripts {
@Scripts.Render("~/bundles/jqueryval")
<script>
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $('#HinhSP').attr('src', e.target.result);
            };
            reader.readAsDataURL(input.files[0]);
        }
    }
</script>
}

WebApplication/WebApplication/Views/BangSanPham/Delete.cshtml
@model WebApplication.Models.BangSanPham

@{
    ViewBag.Title = "Delete";
}

<h2>Xóa</h2>

<h3>Bạn có chắc chắn xóa ?</h3>
<div>
    <h4>BangSanPham</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Mã SP
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaSP)
        </dd>

        <dt>
            Tên SP
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenSP)
        </dd>

        <dt>
            Giá bán
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GiaBan)
        </dd>

        <dt>
            Giá gốc
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GiaGoc)
        </dd>

        <dt>
            Giá góp
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GiaGop)
        </dd>

        <dt>
            Số lượng tồn
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLuongTon)
        </dd>

        <dt>
            Tên loại
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiSanPham.TenLoai)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-default" /> |
            @Html.ActionLink("Quay Lại", "Index")
        </div>
    }
</div>

WebApplication/WebApplication/Views/BangSanPham/Details.cshtml
@model WebApplication.Models.BangSanPham

@{
    ViewBag.Title = "Details";
}

<h2>Chi Tiết Sản Phẩm</h2>

<div>
    <h4>Bảng sản phẩm</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            Mã Sản Phẩm
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaSP)
        </dd>

        <dt>
            Tên Sản Phẩm
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenSP)
        </dd>

        <dt>
            Giá Bán
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GiaBan)
        </dd>

        <dt>
            Giá Gốc
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GiaGoc)
        </dd>

        <dt>
            Giá Góp
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GiaGop)
        </dd>

        <dt>
            Số Lượng
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLuongTon)
        </dd>

        <dt>
            Tên Loại
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiSanPham.TenLoai)
        </dd>

        <dt>
            Hình Ảnh
        </dt>

        <dd>
            <img id="HinhSP" src="@Url.Action("Details", new { id = Model.id })" width="20%" />
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Chỉnh Sửa", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Quay Lại", "Index")
</p>

WebApplication/WebApplication/Views/BangSanPham/Edit.cshtml
@model WebApplication.Models.BangSanPham

@{
    ViewBag.Title = "Edit";
}

<h2>Chỉnh sửa SP</h2>


@using (Html.BeginForm("Edit", "BangSanPham", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.MaSP, "Mã SP", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.MaSP, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaSP)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenSP, "Tên sản phẩm", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.TenSP, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TenSP)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Loai_id, "Loại", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Loai_id, (IEnumerable<SelectListItem>)ViewData["Loai_id"], new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Loai_id)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaBan, "Giá bán", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.GiaBan, new { @class = "form-control", type = "number" })
                @Html.ValidationMessageFor(model => model.GiaBan)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaGoc, "Giá gốc", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.GiaGoc, new { @class = "form-control", type = "number" })
                @Html.ValidationMessageFor(model => model.GiaGoc)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaGop, "Giá góp", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.GiaGop, new { @class = "form-control", type = "number" })
                @Html.ValidationMessageFor(model => model.GiaGop)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoLuongTon, "Số lượng", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.SoLuongTon, new { @class = "form-control", type = "number" })
                @Html.ValidationMessageFor(model => model.SoLuongTon)
            </div>
        </div>

        <div class="form-group">
            @Html.Label("HinhAnh", "Hình sản phẩm", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("HinhAnh", null, new { type = "file", onchange = "readURL(this);", @class = "form-control" })
                @Html.ValidationMessage("HinhAnh")
                <img id="HinhSP" src="@Url.Action("Details", new { id = Model.id })" width="20%" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay Lại", "Index")
</div>

@section Scripts {
@Scripts.Render("~/bundles/jqueryval")
<script>
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $('#HinhSP').attr('src', e.target.result);
            };
            reader.readAsDataURL(input.files[0]);
        }
    }
</script>
}

WebApplication/WebApplication/Views/BangSanPham/Index.cshtml
@model IEnumerable<WebApplication.Models.BangSanPham>

@{
    ViewBag.Title = "Index";
}

<h2>Bảng Sản Phẩm</h2>

<p style="float:right">
    <button type="button" class="btn">@Html.ActionLink("Thêm", "Create") </button>
</p>
<table id="BangSanPham" class="table table-hover table-striped table-bordered">
    <thead style="background-color:deepskyblue">
        <tr>
            <th>ID</th>
            <th>Mã SP</th>
            <th>Tên sản phẩm</th>
            <th>Giá bán</th>
            <th>Giá gốc</th>
            <th>Giá góp</th>
            <th>Tồn</th>
            <th>Loại</th>
            <th>Hình SP</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.id</td>
                <td>@item.MaSP</td>
                <td>@item.TenSP</td>
                <td>@item.GiaBan.ToString("N0")</td>
                <td>@item.GiaGoc.ToString("N0")</td>
                <td>@item.GiaGop.ToString("N0")</td>
                <td>@item.SoLuongTon.ToString("N0")</td>
                <td>@item.LoaiSanPham.TenLoai</td>
                <td>
                    <img src="@Url.Action("Details", new { id = item.id })" width="150" height="100" />
                </td>
                <td>
                    <a title="Sửa" href="@Url.Action("Edit", new { id = item.id })">
                        <span class="glyphicon glyphicon-pencil"></span>
                    </a>
                    <a title="Chi tiết sản phẩm" href="@Url.Action("Details1", new{id = item.id})">
                        <span class="glyphicon glyphicon-search"></span>
                    </a>
                    <a title="Xóa" href="@Url.Action("Delete", new { id = item.id })">
                        <span class="glyphicon glyphicon-trash"></span>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

@section scripts {
<link href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet" />
<script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script>
    $(document).ready(function () {
        $('#BangSanPham').DataTable();
    });
</script>
}